### ISSUE TITLE
create branch

### ISSUE THREAD

**Issue by aminedarabid** [Elvynia/formation-ensup#1]
Bonjour,

Je n'arrive pas à créer une branch dans le git Elvynia/formation-ensup. 

Cordialement,
Amine DARABID.

**Comment by Elvynia** [comment]
Hello,

Désolé j'ai oublié de vous rappeler qu'il me faut vos pseudos pour vous
ajouter les droits. J'ai trouvé aminedarabid et Vulkan78 pour vous c'est
bon j'ai ajouté les droits, il me faut les autres pseudos.

A+

2017-11-04 11:59 GMT+01:00 aminedarabid <notifications@github.com>:

**Comment by JoseAlexandreGiry** [comment]
Bonjour, 

Voici mon pseudo Github : 
JoseAlexandreGiry

Cordialement, 

GIRY José-Alexandre.

**Comment by R78100** [comment]
Bonjour, voici mon pseudo.

Merci d'avance.

Cordialement,
Rudy TOURROU

**Comment by Elvynia** [comment]
Ok c'est bon je vous ai tous ajoutés.

A+
